public class EmployeeUpdateHelper {/*
    public static void userinemployee(List<user> usr){
        list<Employee__c> e = new list<Employee__c>();
        for(user c : usr){
            Employee__c emp = new Employee__c();
            emp.name = c.firstname+' '+c.lastname;
            emp.first_name__c  =c.firstname;
            emp.last_name__c  =c.lastname;
            emp.email__c  =c.email;
            emp.phone__c  =c.phone;
            e.add(emp);
            
            
        }
       insert e;
        
    }
*/
}