public class Student {
    public String lastName;
    public String firstName;
    public String phone;
    Public String city;
/*

Wrapper class example
*********************
We can create a user defined datatypes by using wrapper class and it only has data members, not methods.
Student s1 = new Student();
s1.lastName = 'Waran';
s1.firstName = 'Lakesh';
s1.phone = '9944513773';
s1.city = 'Vellore';

Student s2 = new Student();
s2.lastName = 'Vel';
s2.firstName = 'Saravanan';
s2.phone = '9999999999';
s2.city = 'Coimbatore';

Student s3=s2;
s2=s1;

System.debug('----S1-----');
System.debug(s1.lastName);
System.debug(s1.firstName);
System.debug(s1.phone);
System.debug(s1.city);
*/
    
    
}